services:
    db:
        build:
            context: .
        image: local/postgres-secure:17.6
        container_name: postgres-secure
        restart: unless-stopped
        env_file: ./.env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d:ro
volumes:
    pgdata:
