services:
    db:
        build:
            context: .
            args:
                PG_TAG: 17.6-trixie
        image: local/postgres-secure:17.6
        container_name: postgres-secure
        restart: unless-stopped
        env_file: ./.env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./scripts:/docker-entrypoint-initdb.d:ro
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\" || exit 1"]
            interval: 30s
            timeout: 5s
            retries: 5
            start_period: 30s
volumes:
    pgdata:
